title: "8-Bit Processor Simulation"
description: "Un proyecto educativo paso a paso que implementa un procesador de 8 bits"

# URLs - Importante para que funcione tanto local como en GitHub Pages
url: "https://caertos.github.io"
baseurl: "/8-BitsProcessor"

# Theme and layout configuration
theme: minima
markdown: kramdown

# Author information
author:
  name: "Carlos Cochero"

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "node_modules/"
  - "package.json"
  - "test/"
  - "src/core/**/*.js"  # Solo excluir JS de src/core (el código de simulación)

# Include archivos específicos
include:
  - "src/core/bit/*.md"
  - "src/core/logicGates/*.md"
  - "src/core/derivedGates/*.md"